version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    volumes:
      - .:/var/www/html
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: MiC0ntr4señ@Segura
      MYSQL_DATABASE: laravel
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
